#!/usr/bin/expect -f

set timeout 20
set ip "120.25.165.230"
set user "root"
set password "nm,./=-098"

spawn ssh -o StrictHostKeyChecking=no $user@$ip "ls -F /etc/nginx/ /etc/nginx/conf.d/ /etc/nginx/sites-enabled/ 2>/dev/null"
expect {
    "yes/no" {
        send "yes\r"
        exp_continue
    }
    "password:" {
        sleep 1
        send -- "$password\r"
        exp_continue
    }
    eof
}
