#!/usr/bin/expect -f

set timeout -1
set ip "120.25.165.230"
set user "root"
set password "nm,./=-098"
set local_path "../frontend/dist/"
set remote_path "/usr/share/nginx/html/"

spawn scp -r -o StrictHostKeyChecking=no $local_path $user@$ip:$remote_path
expect {
    "yes/no" {
        send "yes\r"
        exp_continue
    }
    "password:" {
        sleep 1
        send -- "$password\r"
        exp_continue
    }
    eof
}
