#!/usr/bin/expect -f

set timeout 20
set ip "120.25.165.230"
set user "root"
set password "nm,./=-098"

# 1. Update config locally
# (We will do this in the next step via write_to_file locally, then upload)

# 2. Disable default site and reload
spawn ssh -o StrictHostKeyChecking=no $user@$ip "rm /etc/nginx/sites-enabled/default; nginx -s reload"
expect {
    "yes/no" {
        send "yes\r"
        exp_continue
    }
    "password:" {
        sleep 1
        send -- "$password\r"
        exp_continue
    }
    eof
}
