#!/usr/bin/expect -f

set timeout 20
set ip "120.25.165.230"
set user "root"
set password "nm,./=-098"

spawn ssh -o StrictHostKeyChecking=no $user@$ip "echo '---CHECKING_PATHS---'; ls -d /www/wwwroot/* /var/www/html /usr/share/nginx/html 2>/dev/null; echo '---END_CHECK---'"
expect {
    "yes/no" {
        send "yes\r"
        exp_continue
    }
    "password:" {
        sleep 1
        send -- "$password\r"
        exp_continue
    }
    eof
}
